    // l=arr.size()-2;
    // r=arr.size()-1;
    // while(0<=l){
    //     if(arr[l].second<arr[r].second){
    //         dp[r]=abs(arr[l].first-arr[r].first);
    //         r=l;
    //         l--;
    //     }
    //     else{
    //         dp[l]=abs(arr[l].first-arr[r].first);
    //         l--;
    //     }
    // }